### ISSUE TITLE
在宣怀大道跑步时速度异常

### ISSUE THREAD

**Issue by whitecornflower** [cwlm/SJTU_AutoRun#20]
**Describe the bug**
在默认设置下，宣怀大道计划中，配速有时会高于3min/km，在2-3之间
**To Reproduce**
按照宣怀大道计划运行脚本

**Expected behavior**
跑步过程中希望配速一直低于3min/km，这样成绩一直能被记录

**Screenshots**
<img width="423" alt="配速异常" src="https://github.com/cwlm/SJTU_AutoRun/assets/136238887/f6952331-fd0f-4dfb-9753-7d6d47d09851">

**Comment by cwlm** [comment]
配置文件中的配速为从目标点到目标点的直线时间，在引入随机位置波动后可能导致配速过快
可参考[使用方法-编写跑步计划](https://github.com/cwlm/SJTU_AutoRun/blob/main/documents/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95.md#编写跑步计划)自行修改

**Comment by cwlm** [comment]
之后会在默认配置文件里面适当降低速度
