### ISSUE TITLE
你好，我在运行时遇到了中止错误

### ISSUE THREAD

**Issue by lonebeetle** [cwlm/SJTU_AutoRun#36]
**描述错误**
对错误的描述。
我按照使用方法的步骤做了，也验证了版本号，但是在运行那个基础跑步代码的时候，终端一直输出
[DEBUG 00:35:03 sjtuautorun] ('Emulator status', 'stop')
[DEBUG 00:35:04 sjtuautorun] ('Emulator status', 'stop')
[DEBUG 00:35:05 sjtuautorun] ('Emulator status', 'stop')
[DEBUG 00:35:06 sjtuautorun] ('Emulator status', 'stop')
[DEBUG 00:35:07 sjtuautorun] ('Emulator status', 'stop')
[DEBUG 00:35:08 sjtuautorun] ('Emulator status', 'stop')
.......
然后会在几分钟后中断，显示“模拟器启动超时”，报错的是这行代码“timer = start_script()”

**注明**
我也先打开雷神9并登录了交我办。

**Comment by wfrfred** [comment]
请更新版本后查看问题是否已经解决 谢谢
