### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by lonebeetle** [cwlm/SJTU_AutoRun#40]
**描述错误**
更新了之后运行会输出
[DEBUG 17:08:24 sjtuautorun] ('Emulator status', 'running')
[INFO 17:08:25 sjtuautorun] Android Connected!
[INFO 17:08:29 sjtuautorun] resolution:(1080, 1920)
[WARNING 17:08:29 sjtuautorun] ===================WARNING===================
[WARNING 17:08:29 sjtuautorun] No PLAN_ROOT specified, default value C:\Users\52964\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sjtuautorun\data\plans will be used
[WARNING 17:08:29 sjtuautorun] ====================END====================
然后我看那个雷神的交我办页面会进入自动退出和打开的循环，过一阵就报错模拟器连接不上终止了。

**Comment by cwlm** [comment]
可能是无法识别交我办的更新界面，请尝试提前关闭。
如果问题仍存在请提供截图

**Comment by lonebeetle** [comment]
谢谢，刚刚打开按之前一样操作，但是这次他闪退一次之后帮我打开去跑步了（然后成功了），可能之前是我电脑加载太慢他识别为timeout之类的然后退出了？
