### ISSUE TITLE
执行到去跑步界面无法开始跑步

### ISSUE THREAD

**Issue by Texas-Offical** [cwlm/SJTU_AutoRun#50]
如题，start.py执行到进入“去跑步”界面后抛出错误：
_Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjtuautorun\mygo\run_plan.py", line 37, in start_run
    raise CriticalErr("Cannot start running")
sjtuautorun.constants.custom_exceptions.CriticalErr: Cannot start running_
之后停止运行
在停止运行前蓝字提示：_Trying to initialize input method again._

**Comment by Texas-Offical** [comment]
补充：在停止运行前手动按下跑步能正常运行

**Comment by cwlm** [comment]
交我办把去跑步重定向了，马上修

**Comment by cwlm** [comment]
已修复，请下载最新版
