### ISSUE TITLE
前一天还正常运行，第二天出现报错

### ISSUE THREAD

**Issue by Thronedoct** [cwlm/SJTU_AutoRun#61]
运行
![image](https://github.com/user-attachments/assets/43aaec92-6b5f-4037-9fb9-61c162c801ab)
出现如下报错
![image](https://github.com/user-attachments/assets/35b3688d-10ed-4a9e-894a-090c2b787908)

**Comment by epiphany-yang** [comment]
+1

**Comment by isunthedig** [comment]
+1

**Comment by isunthedig** [comment]
@epiphany-yang @Thronedoct 删掉  sjtuautorun\scripts 文件夹里的main.py里的check_for_updates()就行了
![image](https://github.com/user-attachments/assets/566cfa31-b97a-4f9e-a2eb-6bb06e93fbdf)
就是这个

**Comment by cwlm** [comment]
应该是连不上pypi导致的，会尽快修复

**Comment by epiphany-yang** [comment]
确实是。从pypl部署的就有问题，但是直接下载zip包一切正常

**Comment by cwlm** [comment]
已在#64 修复，请手动`pip install -U sjtuautorun`更新
